id: I3835A5C2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:10:52+00:00'
last_modified: '2022-06-08T08:37:04.886119+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17281
  title: ཇོ་རུའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4704':
      image_group_id: I1KG17613
      title: ''
      total_pages: 300
      order: 1
      base_file: 4704.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
