id: P009100
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG17281
  title: ཇོ་རུའི་རྣམ་ཐར།
  author: ''
  volumes:
    4f77a82ecfd842c193f2b477a2c79572:
      image_group_id: I1KG17613
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
